using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VeterinaryHospitalManagement.Web.Data;

namespace VeterinaryHospitalManagement.Tests.Integration.Billing;

public sealed class InvoiceMigrationScriptTests
{
    [Fact]
    public void AddInvoices_creates_tables_sequence_constraints_and_unique_indexes()
    {
        using var db = new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlServer("Server=localhost;Database=x;Integrated Security=True;TrustServerCertificate=True").Options);
        var migrations = db.Database.GetMigrations().ToList();
        var before = Assert.Single(migrations, x => x.EndsWith("_AutoGenerateDoctorCode"));
        var current = Assert.Single(migrations, x => x.EndsWith("_AddInvoices"));
        var migrator = db.GetService<IMigrator>();
        var up = migrator.GenerateScript(before, current);
        Assert.Contains("CREATE TABLE [Invoices]", up);
        Assert.Contains("CREATE TABLE [InvoiceItems]", up);
        Assert.Contains("CREATE SEQUENCE [InvoiceNumberSequence]", up);
        Assert.Contains("CK_Invoices_PaymentMethod", up);
        Assert.Contains("CK_Invoices_TotalAmount", up);
        Assert.Contains("CK_InvoiceItems_LineTotal", up);
        Assert.Contains("IX_Invoices_VisitId", up);
        Assert.Contains("IX_InvoiceItems_VisitServiceId", up);
        Assert.Contains("ON DELETE NO ACTION", up);
        var down = migrator.GenerateScript(current, before);
        Assert.Contains("DROP TABLE [InvoiceItems]", down);
        Assert.Contains("DROP TABLE [Invoices]", down);
    }
}
