using System.Net;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using VeterinaryHospitalManagement.Tests.Infrastructure.Identity;
using VeterinaryHospitalManagement.Web.Authorization;
using VeterinaryHospitalManagement.Web.Data;
using VeterinaryHospitalManagement.Web.Services.Catalogs;
using VeterinaryHospitalManagement.Web.Services.Identity;
namespace VeterinaryHospitalManagement.Tests.Integration.Catalogs;
[Collection(IdentitySqlServerTestCollection.Name)]
public sealed class MedicineWorkflowSqlServerTests
{
 [IdentitySqlServerFact]public async Task Service_normalizes_updates_audits_and_rejects_stale_version(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);int id;await using(var s=f.Services.CreateAsyncScope()){var service=s.ServiceProvider.GetRequiredService<IMedicineService>();id=await service.CreateAsync(new(actor," med-01 "," Amoxicillin "," amoxicillin "," 500 mg "," viên "));var original=(await service.FindAsync(id))!;await service.UpdateAsync(new(actor,id,original.RowVersion,"Amoxicillin mới","Hoạt chất","250 mg","ml"));await Assert.ThrowsAsync<MedicineConcurrencyException>(()=>service.UpdateAsync(new(actor,id,original.RowVersion,"Sai",null,null,"viên")));}await using var check=f.Services.CreateAsyncScope();var db=check.ServiceProvider.GetRequiredService<ApplicationDbContext>();var x=await db.Medicines.SingleAsync();Assert.Equal("MED-01",x.Code);Assert.Equal("Amoxicillin mới",x.Name);Assert.Equal(1,await db.AuditLogs.CountAsync(a=>a.Action=="Medicine.Created"));Assert.Equal(1,await db.AuditLogs.CountAsync(a=>a.Action=="Medicine.Updated"));}
 [IdentitySqlServerFact]public async Task Manager_can_create_medicine_through_form_and_receptionist_is_forbidden(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);await Add(f,actor,"manager-med@vet.test",SystemRoleNames.Manager);await Add(f,actor,"rec-med@vet.test",SystemRoleNames.Receptionist);using(var rec=Client(f)){await Login(rec,"rec-med@vet.test");Assert.Equal(HttpStatusCode.Forbidden,(await rec.GetAsync("/BackOffice/Medicines")).StatusCode);}using var c=Client(f);await Login(c,"manager-med@vet.test");var page=await c.GetStringAsync("/BackOffice/Medicines/Create");using var form=new FormUrlEncodedContent([new("Code"," med-ui "),new("Name","Thuốc UI"),new("ActiveIngredient","Hoạt chất"),new("Strength","10 mg"),new("Unit","viên"),new("__RequestVerificationToken",Token(page))]);var response=await c.PostAsync("/BackOffice/Medicines/Create",form);Assert.Equal(HttpStatusCode.Redirect,response.StatusCode);await using var scope=f.Services.CreateAsyncScope();Assert.Equal("MED-UI",(await scope.ServiceProvider.GetRequiredService<ApplicationDbContext>().Medicines.SingleAsync()).Code);}
 [IdentitySqlServerFact]public async Task Concurrent_duplicate_code_creates_only_one_medicine(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);async Task<bool> Attempt(string name){try{await using var s=f.Services.CreateAsyncScope();await s.ServiceProvider.GetRequiredService<IMedicineService>().CreateAsync(new(actor,"MED-RACE",name,null,null,"viên"));return true;}catch(MedicineManagementException){return false;}}var results=await Task.WhenAll(Attempt("A"),Attempt("B"));Assert.Equal(1,results.Count(x=>x));await using var check=f.Services.CreateAsyncScope();Assert.Equal(1,await check.ServiceProvider.GetRequiredService<ApplicationDbContext>().Medicines.CountAsync());}
 private static HttpClient Client(IdentitySqlServerWebApplicationFactory f)=>f.CreateClient(new WebApplicationFactoryClientOptions{AllowAutoRedirect=false,BaseAddress=new Uri("https://localhost")});
 private static async Task<string> Start(IdentitySqlServerWebApplicationFactory f){using var c=Client(f);await c.GetAsync("/");await using var s=f.Services.CreateAsyncScope();return await s.ServiceProvider.GetRequiredService<ApplicationDbContext>().Users.Where(x=>x.NormalizedEmail==IdentitySqlServerTestEnvironment.BootstrapAdminEmail.ToUpperInvariant()).Select(x=>x.Id).SingleAsync();}
 private static async Task Add(IdentitySqlServerWebApplicationFactory f,string actor,string email,string role){await using var s=f.Services.CreateAsyncScope();await s.ServiceProvider.GetRequiredService<IUserManagementService>().CreateAsync(new(actor,"Medicine User",email,"Integration.Vet123!",role));}
 private static async Task Login(HttpClient c,string email){var page=await c.GetStringAsync("/Account/Login");using var form=new FormUrlEncodedContent([new("Email",email),new("Password","Integration.Vet123!"),new("RememberMe","false"),new("__RequestVerificationToken",Token(page))]);Assert.Equal(HttpStatusCode.Redirect,(await c.PostAsync("/Account/Login",form)).StatusCode);}
 private static string Token(string html)=>Regex.Match(html,"<input[^>]*name=\"__RequestVerificationToken\"[^>]*value=\"(?<token>[^\"]+)\"").Groups["token"].Value;
}
