using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using VeterinaryHospitalManagement.Tests.Infrastructure.Identity;
using VeterinaryHospitalManagement.Web.Authorization;
using VeterinaryHospitalManagement.Web.Services.Identity;
using VeterinaryHospitalManagement.Web.Services.Veterinarians;
namespace VeterinaryHospitalManagement.Tests.Integration.Veterinarians;
[Collection(IdentitySqlServerTestCollection.Name)]
public sealed class VeterinarianProfileServiceSqlServerTests
{
 [IdentitySqlServerFact] public async Task Create_normalizes_values_and_writes_audit(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var user=await Add(f,actor,"doctor1@vet.test",SystemRoleNames.Veterinarian);await With(f,s=>s.CreateAsync(new(actor,user," Nội khoa ")));await using var scope=f.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>();var p=await db.VeterinarianProfiles.SingleAsync();Assert.Equal("VET-000001",p.DoctorCode);Assert.Equal("Nội khoa",p.Specialty);Assert.Single(await db.AuditLogs.Where(x=>x.Action=="VeterinarianProfile.Created").ToListAsync());}
 [IdentitySqlServerFact] public async Task Create_rejects_non_veterinarian_inactive_and_already_linked_users(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var receptionist=await Add(f,actor,"rec@vet.test",SystemRoleNames.Receptionist);await Assert.ThrowsAsync<VeterinarianManagementException>(()=>With(f,s=>s.CreateAsync(new(actor,receptionist,null))));var inactive=await Add(f,actor,"inactive@vet.test",SystemRoleNames.Veterinarian);await using(var scope=f.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>();(await db.Users.FindAsync(inactive))!.IsActive=false;await db.SaveChangesAsync();}await Assert.ThrowsAsync<VeterinarianManagementException>(()=>With(f,s=>s.CreateAsync(new(actor,inactive,null))));var active=await Add(f,actor,"active@vet.test",SystemRoleNames.Veterinarian);await With(f,s=>s.CreateAsync(new(actor,active,null)));await Assert.ThrowsAsync<VeterinarianManagementException>(()=>With(f,s=>s.CreateAsync(new(actor,active,null))));}
 [IdentitySqlServerFact] public async Task Sequential_creates_receive_distinct_generated_codes(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var a=await Add(f,actor,"a@vet.test",SystemRoleNames.Veterinarian);var b=await Add(f,actor,"b@vet.test",SystemRoleNames.Veterinarian);await With(f,s=>s.CreateAsync(new(actor,a,null)));await With(f,s=>s.CreateAsync(new(actor,b,null)));await using var scope=f.Services.CreateAsyncScope();var codes=await scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>().VeterinarianProfiles.OrderBy(x=>x.DoctorCode).Select(x=>x.DoctorCode).ToListAsync();Assert.Equal(["VET-000001","VET-000002"],codes);}
 [IdentitySqlServerFact] public async Task Concurrent_duplicate_user_creates_only_one_profile(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var user=await Add(f,actor,"same-user@vet.test",SystemRoleNames.Veterinarian);var results=await Task.WhenAll(Attempt(()=>With(f,s=>s.CreateAsync(new(actor,user,null)))),Attempt(()=>With(f,s=>s.CreateAsync(new(actor,user,null)))));Assert.Equal(1,results.Count(x=>x));await using var scope=f.Services.CreateAsyncScope();Assert.Equal(1,await scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>().VeterinarianProfiles.CountAsync());}
 [IdentitySqlServerFact] public async Task Audit_failure_rolls_back_profile_creation(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var user=await Add(f,actor,"rollback@vet.test",SystemRoleNames.Veterinarian);await Assert.ThrowsAsync<VeterinarianManagementException>(()=>With(f,s=>s.CreateAsync(new("missing-actor",user,null))));await using var scope=f.Services.CreateAsyncScope();Assert.Equal(0,await scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>().VeterinarianProfiles.CountAsync());}
 [IdentitySqlServerFact] public async Task Update_stale_version_writes_no_false_audit_and_activation_is_audited(){await IdentitySqlServerTestEnvironment.RecreateAndMigrateAsync();using var f=new IdentitySqlServerWebApplicationFactory();var actor=await Start(f);var user=await Add(f,actor,"stale@vet.test",SystemRoleNames.Veterinarian);var id=await With(f,s=>s.CreateAsync(new(actor,user,null)));var original=(await With(f,s=>s.FindAsync(id)))!;await With(f,s=>s.UpdateAsync(new(actor,id,original.RowVersion,"Ngoại khoa")));await Assert.ThrowsAsync<VeterinarianConcurrencyException>(()=>With(f,s=>s.UpdateAsync(new(actor,id,original.RowVersion,"Sai"))));var latest=(await With(f,s=>s.FindAsync(id)))!;await With(f,s=>s.SetActiveAsync(new(actor,id,latest.RowVersion,false)));await using var scope=f.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>();Assert.Equal(1,await db.AuditLogs.CountAsync(x=>x.Action=="VeterinarianProfile.Updated"));Assert.Equal(1,await db.AuditLogs.CountAsync(x=>x.Action=="VeterinarianProfile.Deactivated"));Assert.Equal("Ngoại khoa",(await db.VeterinarianProfiles.SingleAsync()).Specialty);}
 static async Task<bool> Attempt(Func<Task> action){try{await action();return true;}catch(VeterinarianManagementException){return false;}}
 static async Task<T> With<T>(IdentitySqlServerWebApplicationFactory f,Func<IVeterinarianProfileService,Task<T>> call){await using var s=f.Services.CreateAsyncScope();return await call(s.ServiceProvider.GetRequiredService<IVeterinarianProfileService>());} static async Task With(IdentitySqlServerWebApplicationFactory f,Func<IVeterinarianProfileService,Task> call){await using var s=f.Services.CreateAsyncScope();await call(s.ServiceProvider.GetRequiredService<IVeterinarianProfileService>());}
 static async Task<string> Start(IdentitySqlServerWebApplicationFactory f){using var c=f.CreateClient();await c.GetAsync("/");await using var s=f.Services.CreateAsyncScope();return await s.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>().Users.Where(x=>x.NormalizedEmail==IdentitySqlServerTestEnvironment.BootstrapAdminEmail.ToUpperInvariant()).Select(x=>x.Id).SingleAsync();}
 static async Task<string> Add(IdentitySqlServerWebApplicationFactory f,string actor,string email,string role){await using var s=f.Services.CreateAsyncScope();await s.ServiceProvider.GetRequiredService<IUserManagementService>().CreateAsync(new(actor,"Doctor Test",email,"Integration.Vet123!",role));return await s.ServiceProvider.GetRequiredService<Web.Data.ApplicationDbContext>().Users.Where(x=>x.Email==email).Select(x=>x.Id).SingleAsync();}
}
